baseURL = 'https://arendesai.com/'
languageCode = 'en-us'
title = 'arendesai.com'
theme = 'mainroad'

# Mainroad Config
[Params.style.vars]
  highlightColor = "#556b2f"

[menu]

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 10

  [[menu.main]]
    identifier = "coursework"
    name = "Coursework"
    url = "/coursework/"
    weight = 10

  [[menu.main]]
    identifier = "datascience"
    name = "Data Science"
    url = "/datascience/"
    weight = 10

  [[menu.main]]
    identifier = "computergraphics"
    name = "Computer Graphics"
    url = "/computergraphics/"
    weight = 10

  [[menu.main]]
    identifier = "robotics"
    name = "Robotics"
    url = "/robotics/"
    weight = 10

[params.theme]
palette = "base16-dark"

[Author]
name = "Aren Desai"
bio = "Graphics Programmer and ML Engineer"
avatar = "static/face.jpeg"

[params.about]
title = "arendesai.com"
description = "Aren Desai's (somewhat) professional website!"
#logo_image = "images/rice.svg"
#
[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/ArenKDesai"

[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

# URL specifies the Go Cloud Development Kit URL to deploy to. Examples:
URL = "gs://arendesai.com"

