name: Build Hugo Site and Deploy to GCS

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for GCP authentication and content access
permissions:
  contents: read
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "gcp-deploy"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          cd arendesai.com && hugo

      - name: Manually copy images
        run: |
          cp -r arendesai.com/static/* arendesai.com/public

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/70577247397/locations/global/workloadIdentityPools/arendesai-com-pool/providers/github
          service_account: github-website-deployer@personal-431100.iam.gserviceaccount.com

      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: './arendesai.com/public' # The local path to your website's build output
          destination: 'arendesai.com' # Your GCS bucket name
          parent: false # Set to false if you want files directly at the bucket root
          gzip: true # Optional: Gzip files for better performance