name: Deploy Website to GCS

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Option 1: Authenticate with Workload Identity Federation (Recommended)
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/70577247397/locations/global/workloadIdentityPools/arendesai-com-pool/providers/github
          service_account: 70577247397-compute@developer.gserviceaccount.com

      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: './threejs-arendesai.com' # The local path to your website's build output or static files
          destination: 'arendesai.com' # Your GCS bucket name
          parent: false # Set to false if you want files directly at the bucket root
          gzip: true # Optional: Gzip files for better performance
          predefinedAcl: 'publicRead' # Optional: Make uploaded objects publicly readable for a static website
